'use strict';

const ENABLE_RECORDING = false;
const ENABLE_RECORDING_REALTIME = false;
const ENABLE_RECORDING_TEST_LAMBDA = false;

const MIN_FRAMES_TO_LIST = 1000;
const MAX_ROLL_LENGTH = ENABLE_RECORDING_REALTIME ? 10 : 100;